### ISSUE TITLE
when type npm run dev has erroe:

### ISSUE THREAD

**Issue by Vladi-oss** [xitanggg/open-resume#32]
> open-resume@0.1.0 dev
> next dev

/home/User/Рабочий стол/open-resume-main/node_modules/next/dist/cli/next-dev.js:257
            showAll: args["--show-all"] ?? false,
                                         ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.dev (/home/User/Рабочий стол/open-resume-main/node_modules/next/dist/lib/commands.js:15:30)
    at Object.<anonymous> (/home/User/Рабочий стол/open-resume-main/node_modules/next/dist/bin/next:150:28)
    at Module._compile (internal/modules/cjs/loader.js:999:30)

**Comment by LexaNoN** [comment]
me too

**Comment by Edouard360** [comment]
What version of node are you using? 
For me, using `nvm use v18.16.0` fixed the issue, I think any version above 18 should work.
The dockerfile specifies the version 18, but ideally package.json should specify it too in the "engines" section?
